version: '3'
services:
  # Message broker rabbitmq
  rabbitmq:
    image: "rabbitmq:management"
    mem_limit: 100M
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  #Service for the recetas application
#  auth:
#    image: rapidbetauth:latest
#    mem_limit: 500M
#    ports:
#      - "3001:3001"
##    environment:
#
#    depends_on:
#      - postgres_auth
#      - rabbitmq

  # PostgreSQL database service for auth application
  postgres_auth:
    image: postgres:latest
    # mem_limit: 50M
    container_name: postgres_auth
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPORT: 5433
    ports:
      - "5433:5433"
  # MySQL database service for bets application
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_bets
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
  # PostgreSQL database service for userbets application
#  postgres_userbets:
#    image: postgres:latest
#    mem_limit: 50M
#    container_name: postgres_userbets
#    environment:
#      POSTGRES_DB: mydb
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      PGPORT: 5435
#    ports:
#      - "5435:5435"